### ISSUE TITLE
APP 模块巨复杂

### ISSUE THREAD

**Issue by yeahfo** [mryqr-com/mry-backend#11]
整个项目 APP 模块巨复杂 如果没有循序渐进的业务和实现步骤的文档介绍，完全理解不了里面的业务逻辑和思想

**Comment by wwe1959765733** [comment]
脑袋不好使就别干这一行

**Comment by yeahfo** [comment]
> 脑袋不好使就别干这一行

谁家的狗没拴好绳，乱咬人很有忧郁感？

**Comment by wwe1959765733** [comment]
笑死 你是泰迪？只会怼天怼地 看不懂代码 真可怜
