### ISSUE TITLE
关于一些非聚合根但是必须持久化的疑惑

### ISSUE THREAD

**Issue by yeahfo** [mryqr-com/mry-backend#9]
比如产品要求一些简单的下拉选也能够动态配置，比如码如云里面的Plan, 或者某个type, 或者某个现有的枚举，但是将它们配备repository applicationservice 感觉很诡异，我尝试的做法是将聚合根当成它们factory，处理完saveXXX

**Comment by lxqgithub** [comment]
大佬你说的问题 我也比较困扰。但我没看明白你的处理方法。能截个图看看代码实现吗？

**Comment by yeahfo** [comment]
> 大佬你说的问题 我也比较困扰。但我没看明白你的处理方法。能截个图看看代码实现吗？

没有什么的，ddd只是一种范式，尽量遵守即可，不必要纠结按部就班，因为根本就没有按部就班存在，都是拍脑门的事

**Comment by yeahfo** [comment]
> 大佬你说的问题 我也比较困扰。但我没看明白你的处理方法。能截个图看看代码实现吗？

如果真的有那种所谓的方法，那些ddd的书早就声明了，而不是如你现在一样疑惑，就像现实生活中抽烟喝酒嚼槟榔是有害的，但是这些依然存在而且还很滋润
